In [1]:
#                                  @ DATA ANYLYSIS WITH PYTHON
# In this tutorial we going to do data analysis / science in python using pandas , numpy , matplot-lib and scikit-learn etc.



# What  is specifically data analytics ?
#-----> Is likely a process of analyzing the large set of data and solving the queries for the data set , visualizing it , and 
#   by doing the process and modelling the data set we can make summary on the result of the data and make predictions for the
#   future actions.


# As we know , we can do such process in different domains like sql , bi tools or in excel. So lets understand the need of 
# python over such formats.


# Well from my experience , you need to know all the tools as individual has its  specific advantages. 
# So i will tell you When and why you need to use python, sql and excel or bi tools. 

# Now first understand the ease of this tools in data analysis
#1) SQL and python --> used to process data.
#2) Python , excel and bi tools --> used to visualize the data.

# 1) Data processing : It includes data cleaning , mining and connecting different data sets in order to make the desired data set.
# It depends on the purpose which tool you need to use.
# Now lets get started with the selection :
#----> You  can use sql for connecting different databases and combine it into a single one and with the simple code you can ask 
#queries to the data , it is better to use sql here. Simply if we want to retrieve data go for sql , but sql have certain range
#of functions , so at this point if we want to perform some computation and mathematical operations on the data you use python libraries.

#2) Data Visualization:
# Why python not excel and why bi tools plays a vital role here ?
# ---->So we can do such queries in excel itself but it comes to  large data sets excel fails at the speed and the accuracy as excel
# dont have such functions that can deal with larger data sets. But bi tools are more useful in visualizing data and it can 
#deal with the large data sets and visualization in bi tools is better than python because you can modify the data set and
#As it is a software ,so instead of writing code you can use the tools directly and make changes in the process and its too simple 
#If you write a complex code sometimes it is too difficult to find the error and visulaize the data in porper order.
#Bi tools offers you separated domain of transforming and modelling the data. So using bi tools are useful in visualization ,
# but knowing python libraries are good for the simple tasks , as you need not to shift the paltform , its time consuming and 
# you need to think in different ways.


#As in our data set there may be null values or kind of raw things , so in order to get the desired data , we need to clean the
# data this process is known as data 'munging'or 'wrangling'.




# So lets get started with the python :


#  Numpy : Numpy stands for numerical python as is heavily used in the scientific computing.
        # It basically deals with N-D arrays. For the data science is important as it provides a efficient interface to store
        # and process the dense data. We can perform lots data operation with in just few line of code and that makes the code 
        # simple and it is comfertable when you have to look at code for the changes.
    
import numpy as np  # importing numpy module 
arr = np.array([1,2,3])   # creatring an object(array) in numpy
print(arr)

# As we can see it is quite similar as list (1-D) and we can do same operations as we do for list such as indexing , slicng
# adding and removing etc. 

#But Why to use numpy then?
# ------> First ,the numpy is a multi-D Array library so we can do matrix calculations and can operate the large data sets 
# As in list , while storing the 1 byte array in memory location , the each array points memory location in scattered way and
# we need to store lots info about the data ( and this takes more space and then the process becomes slow and it is complex too),
# that's why array stored in dicontinious manner , but the numpy utilizes contigious memory so uses less memory.
# we can perform bit-wise operation(Most useful in ML) in numpy which is not possible in lists.
# And the main reason to use numpy is , it can operate large data sets.


#lets perform some basic operations and then we go for numpy for data science

#1) Indexing :
print(arr[2])
add = arr[0] + arr[1]
print(add)

arr1 = np.array([[1,2,3] , [4,5,6]])
print(arr1)
print('2nd element of 1st row is : ' , arr1[0 , 1])  #[row , col]
print('last element of 2nd row is : ' , arr1[1 , -1])
print('1st row elemets for different cols : ' , arr1[0 , (0 , 2)])  # passing a tuple 



# sorting 
print('descending oreder:',np.sort(arr1)[::-1])   #back ordering



# Boolean Mask :
# In the indexing we can get the desired elements even random positions by using boolean indexing
d = arr1 > 3   # if we want elements greater than 3
print('elements greater than 3 : ' , arr1[d])
arr1[d] = 0
print(arr1 )  # if we want to make the change in the selected elements 
print('elements divisible by 3 : ' , arr1[arr1%3==0])

#Slicing & indexing in lists is lengthy as we need to looped the entire list while in numpy we can directly access the desired one

#2) Slicing :
print('1st row of arr1 is :' , arr1[ 0 , : ])
print('2nd col of arr1 is :' , arr1[ : , 1])

for row in arr1:
    print('iterated rows:' , row)  

for i in arr1.flat:
    print('flat the matrix:' , i)
    

# if we wants elements of the array ordered by row or col . As above using flat we can get the elements by row but the same thing 
# wecan do with a nditer() function

for x in np.nditer(arr1 , order  = 'C'): # row by row
    print( x)
    
for y in np.nditer(arr1 , order = 'F'): # col by col
    print( y)
    





# we can stck 2 arrays by using stack()
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print('vertically stacked array' , np.vstack((a,b))) # its [a/b] form 
print('horizontally stacked array' , np.hstack((a,b)))  # its [a:b] form
    
# As above we fit tow different arrays into one single , so now if we have a big array we can split  it into 2 or more different
# arrays using split() function
c = np.arange(20).reshape(2,10)
print('vertically split arrays:' , np.vsplit(c , 2))
print('vertically split arrays:' , np.hsplit(c , 2))



#3) Data types : Python uses in-built data types such as integer , float , strings , boolean and complex but numpy offers more 
# data types as following
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

# with this we can do some useful operations
print(arr1.dtype)  # getting data type of arr1
arr2 = np.array([11,22,33] , dtype = 'S')  # creating a string data type
print(arr2)
arr3 = np.array([2,4,6] , dtype = 'i4')   # 4 bytes integer
print(arr3)          # but remember we can't convert a string to integer 
arr4 = arr3.astype('f')  # changing integer to float
print(arr4)  # you can directly write float also

# Now if we have data  and need to transform it for different purposes , so we required the oroginal data for each task in order
# to modifying it. In this situation we can use copy() function and modify the data.

copy_arr = arr1.copy()  # copy should not affect the original array
copy_arr[0 , 0] = 0
print(copy_arr)
print(copy_arr.base)


print('size of arr1 is :' , arr1.shape)   # shape is the number of elements in each dimensions ( row * col )
print('total no of elements :' , arr1.size) # size gives total no of elements in the array
print('dimensions of arr1:' , arr1.ndim)   # ndimm gives dimension of given array
nd_arr = np.array([[1,2,3] , [1,2,3]] , ndmin = 3)  # creating 3-D array with ndmin(takes an integer)
print(nd_arr) 
print(nd_arr.shape)

#we can reshape our 1-D array  
arr5 = np.array([1,2,3,4,5,6,7,8,9])
reshape_arr = arr5.reshape(3,3) #reshape(row , col)
print(reshape_arr)
print(reshape_arr.shape)
print('reshaped arr1:' , arr1.reshape(3,2))  # reshape the arr1 to (3,2)
print('N-d to 1-D for arr1:' , arr1.ravel()) # ravel() converts every N-D array to 1-D (all rows to one single rows)

arr6 = np.arange(0 , 9).reshape(3,3)  # we  can create a simple array containing 0 - 10 no.s using arange similar as the range in lists.
print(arr6)    #(start , end , step)

# same as above with linspace we can create a array of bunch of no.s with in the range 
arr7 = np.linspace(1 , 2 , 10)  # gives me 10 no.s in the range of 1 - 2
print(arr7)
# Sometimes we need to initialize the array (commonly in ML ) so for that we can create an array with zeros of desired shape
zeros = np.zeros((3,3) , dtype = 'i')  # pass the shape
print(zeros)
# and also we can create a array of all one using ones
ones = np.ones((3,3) , dtype = 'i')
print(ones)



[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
2nd element of 1st row is :  2
last element of 2nd row is :  6
1st row elemets for different cols :  [1 3]
descending oreder: [[4 5 6]
 [1 2 3]]
elements greater than 3 :  [4 5 6]
[[1 2 3]
 [0 0 0]]
elements divisible by 3 :  [3 0 0 0]
1st row of arr1 is : [1 2 3]
2nd col of arr1 is : [2 0]
iterated rows: [1 2 3]
iterated rows: [0 0 0]
flat the matrix: 1
flat the matrix: 2
flat the matrix: 3
flat the matrix: 0
flat the matrix: 0
flat the matrix: 0
1
2
3
0
0
0
1
0
2
0
3
0
vertically stacked array [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
horizontally stacked array [[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]
vertically split arrays: [array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]
vertically split arrays: [array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]]), array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])]
int32
[b'11' b'22' b'33']
[2 4 6]
[2. 4. 6.]
[[0 2 3]
 [0 0 0]]
None
size of

In [41]:
# Now lets perform some maths operations on array
arr = np.array([1,2,3])
arr1 = np.array([4,5,6])
print('sum of arr + arr1 :' , arr + arr1)  # in list we need to use list comprehension to do such operations
print('add fun : ' , np.add(arr,arr1))
print('sub of arr + arr1 :' , arr1 - arr)  # but  in numpy its so simple to do this as we need to write basic a+b
print('product of arr + arr1 :' , arr * arr1) # It will do bit - wise operation (1 of arr + 1st of arr1)
print('div of arr + arr1 :' , arr1 / arr) 



print('matrix product of arr and arr1:' , arr.dot(arr1))
print('simple method matrix product of arr and arr1:' , arr@arr1)
print('elementwise multi :' , arr*arr1)    # as numpy performs element/bitwise operations(its an very big advantage over list




a1 = np.array([[1,2,3] , [4,5,6]])  

print(a1)
print('min no of a1:' , a1.min())      # you can see what are math operations by np.(tab on keyboard) 
print('max no of a1:' , a1.max())
print('min no of each row:' , a1.min(axis=1))     # min for each row using axis(1-->row and 0-->cols)
print('max no of each row:' , a1.max(axis=1))
print('min no of each col:' , a1.min(axis=0))
print('max no of each col:' , a1.max(axis=0))
print('sum no of a1:' , a1.sum())
print('mean1 no of a1:' , np.mean(a1)) 
print('mean1(avg) no of a1:' , a1.sum()/a1.size) 

print('sum of each row elements:' , a1.sum(axis = 1)) # axis is basically for to indexing row and col
print('sum of each col elements:' , a1.sum(axis = 0))  # 0 for col and 1 for the row
print('square root of each element in array:' , np.sqrt(a1))
print('stnadard deviation:' , np.std(a1))
print('square :' , np.square(a1))    # a1 ** 2  we can take any power
print('Transpose of a1 :' , a1.T)
print('Exponential of each element :' , np.exp(a1))


# we can create a function for the data
def math_operations(x,y):
    return x+y
   

z = np.fromfunction(math_operations , (3,3) , dtype='i')
print(z)
    


sum of arr + arr1 : [5 7 9]
add fun :  [5 7 9]
sub of arr + arr1 : [3 3 3]
product of arr + arr1 : [ 4 10 18]
div of arr + arr1 : [4.  2.5 2. ]
matrix product of arr and arr1: 32
simple method matrix product of arr and arr1: 32
elementwise multi : [ 4 10 18]
[[1 2 3]
 [4 5 6]]
min no of a1: 1
max no of a1: 6
min no of each row: [1 4]
max no of each row: [3 6]
min no of each col: [1 2 3]
max no of each col: [4 5 6]
sum no of a1: 21
mean1 no of a1: 3.5
mean1(avg) no of a1: 3.5
sum of each row elements: [ 6 15]
sum of each col elements: [5 7 9]
square root of each element in array: [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
stnadard deviation: 1.707825127659933
square : [[ 1  4  9]
 [16 25 36]]
Transpose of a1 : [[1 4]
 [2 5]
 [3 6]]
Exponential of each element : [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [3]:
import pandas as pd
from sklearn.datasets import load_wine   
data = load_wine()
wine_arr = pd.DataFrame(data["data"] , columns = data['feature_names'])
#print(wine_arr)

res1 = wine_arr['magnesium']
res2 = wine_arr['color_intensity']
print(res1)
print(res2)


0      127.0
1      100.0
2      101.0
3      113.0
4      118.0
       ...  
173     95.0
174    102.0
175    120.0
176    120.0
177     96.0
Name: magnesium, Length: 178, dtype: float64
0       5.64
1       4.38
2       5.68
3       7.80
4       4.32
       ...  
173     7.70
174     7.30
175    10.20
176     9.30
177     9.20
Name: color_intensity, Length: 178, dtype: float64


In [5]:
import pandas as pd
from sklearn.datasets import load_wine    #scikit-learn is basically a ML pytho library to load datasets 
data = load_wine()
wine_arr = pd.DataFrame(data["data"] , columns = data['feature_names'])
print(wine_arr)
print(wine_arr.shape)
print(data["feature_names"])


     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyan

In [8]:
# if - then logic using np.where(array_condition , (x,y)) if condition is true ----> x and if its false ----> y
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine    #scikit-learn is basically a ML pytho library to load datasets 
data = load_wine()
wine_arr = data['data']
np.where(wine_arr[: , 0] < 12 , 'low alcohol',
        np.where(wine_arr[: , 0] > 14 , 'high alcohol' , 'medium alcohol' ))


array(['high alcohol', 'medium alcohol', 'medium alcohol', 'high alcohol',
       'medium alcohol', 'high alcohol', 'high alcohol', 'high alcohol',
       'high alcohol', 'medium alcohol', 'high alcohol', 'high alcohol',
       'medium alcohol', 'high alcohol', 'high alcohol', 'medium alcohol',
       'high alcohol', 'medium alcohol', 'high alcohol', 'medium alcohol',
       'high alcohol', 'medium alcohol', 'medium alcohol',
       'medium alcohol', 'medium alcohol', 'medium alcohol',
       'medium alcohol', 'medium alcohol', 'medium alcohol',
       'high alcohol', 'medium alcohol', 'medium alcohol',
       'medium alcohol', 'medium alcohol', 'medium alcohol',
       'medium alcohol', 'medium alcohol', 'medium alcohol',
       'medium alcohol', 'high alcohol', 'medium alcohol',
       'medium alcohol', 'medium alcohol', 'medium alcohol',
       'medium alcohol', 'high alcohol', 'high alcohol', 'medium alcohol',
       'high alcohol', 'medium alcohol', 'medium alcohol',
       'mediu

In [9]:
# sorting entire dataset wrt just one col using np.argsort()
a = np.argsort(wine_arr[: , 0])[: : -1]
wine_arr[a][: , :3]

array([[14.83,  1.64,  2.17],
       [14.75,  1.73,  2.39],
       [14.39,  1.87,  2.45],
       [14.38,  1.87,  2.38],
       [14.38,  3.59,  2.28],
       [14.37,  1.95,  2.5 ],
       [14.34,  1.68,  2.7 ],
       [14.3 ,  1.92,  2.72],
       [14.23,  1.71,  2.43],
       [14.22,  3.99,  2.51],
       [14.22,  1.7 ,  2.3 ],
       [14.21,  4.04,  2.44],
       [14.2 ,  1.76,  2.45],
       [14.19,  1.59,  2.48],
       [14.16,  2.51,  2.48],
       [14.13,  4.1 ,  2.74],
       [14.12,  1.48,  2.32],
       [14.1 ,  2.16,  2.3 ],
       [14.1 ,  2.02,  2.4 ],
       [14.06,  2.15,  2.61],
       [14.06,  1.63,  2.28],
       [14.02,  1.68,  2.21],
       [13.94,  1.73,  2.27],
       [13.9 ,  1.68,  2.12],
       [13.88,  5.04,  2.23],
       [13.88,  1.89,  2.59],
       [13.87,  1.9 ,  2.8 ],
       [13.86,  1.35,  2.27],
       [13.86,  1.51,  2.67],
       [13.84,  4.12,  2.38],
       [13.83,  1.57,  2.62],
       [13.83,  1.65,  2.6 ],
       [13.82,  1.75,  2.42],
       [13

In [11]:
# lets get numpy arrays using pandas
import pandas as pd
import pandas as pd
from sklearn.datasets import load_wine    #scikit-learn is basically a ML pytho library to load datasets 
data = load_wine()
wine_arr = pd.DataFrame(data["data"] , columns = data['feature_names'])
df = pd.DataFrame(wine_arr , columns = data['feature_names'] )
df.head()
#df.tail()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [12]:
df.values   # its our numpy array by using values

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [24]:
#  Now we going in advance in numpy
# get no closest to 0.50
import numpy as np
a = np.random.random(100).reshape(20,5)
a = abs(a-.5)
np.argmin(a , axis=0)  #argmin() returns the indices with min values along an axis
np.argmin(a , axis=1)


array([3, 1, 2, 1, 3, 4, 3, 1, 1, 2, 1, 3, 2, 0, 2, 3, 3, 3, 3, 1],
      dtype=int64)

In [25]:
a

array([[0.44452823, 0.13954579, 0.0967838 , 0.04197521, 0.18376109],
       [0.32315246, 0.11717088, 0.22801986, 0.28846672, 0.16498488],
       [0.31774196, 0.22823463, 0.04643368, 0.21274316, 0.22928979],
       [0.27914591, 0.2106228 , 0.40437033, 0.38046486, 0.45086942],
       [0.31584634, 0.10935879, 0.28914772, 0.07689739, 0.13315302],
       [0.26558545, 0.25585541, 0.47905207, 0.49447893, 0.03553181],
       [0.13484391, 0.155388  , 0.1106783 , 0.08524597, 0.13613984],
       [0.0138787 , 0.0117464 , 0.41843024, 0.09621887, 0.14614266],
       [0.298126  , 0.04801199, 0.11637298, 0.22543957, 0.26631068],
       [0.04412994, 0.30724822, 0.03340784, 0.1228352 , 0.10826535],
       [0.14572314, 0.0480725 , 0.21737966, 0.12986583, 0.40427355],
       [0.46678662, 0.31371465, 0.28691479, 0.07344075, 0.2857355 ],
       [0.27883374, 0.24055231, 0.20043697, 0.404664  , 0.46995046],
       [0.07898367, 0.14205113, 0.10013672, 0.11444321, 0.30342837],
       [0.23191774, 0.11155719, 0.

In [34]:
# select top cols  on order of high variance
b = np.random.random(100).reshape(10,10)
b = np.var(b , axis=0)   # list of variance for every col
maxorder = np.argsort(b)   # returns indices on order wrt variance 
c = maxorder[-5:]
#b[:,c]
print(c)

[5 4 9 1 0]


In [49]:
#  Broadcasting : Corresponds to lots operations of numpy (mostly matrix)


# Dense layer calculations in numpy : neural network part 
# formula for 2nd layer elements of a neural network ---> A * [W] + b =[B]  W=wieght , b=bias a==input array/data

import numpy as np
Input_layer = np.random.random(20)
Hidden_layer = np.random.randn(500 , 20)  # 500 neurons in hidden layer(1st)
Bias_vals = np.random.random(500)  # getting some bias values

Output_layer = np.dot(Hidden_layer,Input_layer) + Bias_vals
#print(Output_layer)
print(np.maximum(0,Output_layer))    # making -ve as 0 


[3.60773950e+00 1.67835231e+00 0.00000000e+00 3.90714813e-01
 0.00000000e+00 3.69279556e-01 0.00000000e+00 4.12787569e-01
 0.00000000e+00 2.27014138e+00 4.06943848e-02 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.27928093e-01 1.02919338e+00
 5.37090394e+00 4.51018920e-01 0.00000000e+00 1.79344777e-01
 0.00000000e+00 6.93840906e+00 0.00000000e+00 1.28420688e-01
 9.64582798e-01 0.00000000e+00 3.79789979e+00 2.47601578e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 3.79658176e+00 8.59193531e-01 0.00000000e+00 0.00000000e+00
 1.94830207e+00 0.00000000e+00 0.00000000e+00 3.69247175e+00
 2.93445070e+00 0.00000000e+00 3.16039306e+00 3.71516214e+00
 9.20607472e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 8.67623435e-01 0.00000000e+00
 6.43262004e+00 0.00000000e+00 5.68378600e+00 3.46940704e+00
 0.00000000e+00 3.43840358e+00 0.00000000e+00 0.00000000e+00
 4.51700640e+00 0.00000000e+00 7.93318436e-01 0.00000000e+00
 0.00000000e+00 0.000000